config/routes.rb
Trello::Application.routes.draw do
  root "static_pages#root"
  
  resources :users
  resource :session
  
  
  namespace :api, defaults: { format: :json }  do
    resources :boards, except: [:new, :edit]
    resources :lists, only: [:create, :update, :destroy]
    resources :cards, only: [:create, :update, :destroy, :show]
    resources :items, only: [:create, :update, :destroy]
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :lists, dependent: :destroy
  has_many :board_memberships, dependent: :destroy
  has_many :members, through: :board_memberships, source: :user
end

app/models/board_membership.rb
class BoardMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  has_many :items, dependent: :destroy
  has_many :card_assignments, dependent: :destroy
  
  # default_scope { order(:ord) }
end

app/models/card_assignment.rb
class CardAssignment < ActiveRecord::Base
  belongs_to :card
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  belongs_to :card
  
end

app/models/list.rb
class List < ActiveRecord::Base
  
  belongs_to :board
  has_many :cards, dependent: :destroy
  
  # default_scope { order(:ord) }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :firstname, presence: true
  validates :password, length: { minimum: 4, allow_nil: true }

  
  has_many :boards
  has_many :board_memberships
  has_many :card_assignments
  
  attr_reader :password
  after_initialize :ensure_session_token
  
  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password    
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
  
  def set_initials
    self.initials = self.firstname[0].upcase + self.lastname[0].upcase
  end
  
  protected
  
  def ensure_session_token 
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?
  
  private
  
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end
  
  def signed_in?
    !!current_user
  end
  
  def sign_in!(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end
  
  def sign_out!
    @current_user.try(:reset_session_token!)
    session[:token] = nil
  end
  
  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:user])
    
    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["invalid email or password"]
      render :new
    end
  end
  
  def destroy
    sign_out!
    redirect_to new_session_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end
  
  def create
    @user = User.new(user_params)
    @user.set_initials
    
    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kyllo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

</head>
<body class="index">
	<% if signed_in? %>
	<div class="header">
		<div class="header-boards">
			<i class="fa fa-trello b-logo"></i>
			Boards
		</div>

		<div class="logo">
			<a id="logo-link" href="/"><i class="fa fa-trello"></i> Kyllo</a>
		</div>
		
		<div class="header-info">
		
		
			<div class="dropdown name-box">
				<button class="drop-btn dropdown-toggle" type="button" id="logout-menu" data-toggle="dropdown">
					<div class="btn-initials"><%= current_user.initials %></div>
					<div class="btn-name"><%= current_user.firstname.capitalize + " " + current_user.lastname.capitalize %></div>
				</button>
				<ul class="dropdown-menu" role="menu" aria-labelledby="logout-menu">
					<li class="dropdown-name" role="presentation">
						<%= current_user.firstname.capitalize + " " + current_user.lastname.capitalize %> 
					</li>
					
					<li role="presentation" class="divider"></li>
					<li role="presentation">
						<%= link_to "Log Out", session_url, method: :delete, class: 'signout', role: 'menuitem' %>
					</li>
				</ul>
			</div>
			
		</div>
	</div>
	
	<% end %>
	<%= yield %>
	


</body>
</html>